INSERT INTO products (id, name, category, description, price, quantity) VALUES
  (1, 'Laptop Pro 15"', 'Computers', 'High-performance 15-inch laptop for professionals', 1299.99, 10),
  (2, 'Laptop Air 13"', 'Computers', 'Lightweight and portable 13-inch laptop', 999.99, 15),
  (3, 'Wireless Mouse', 'Accessories', 'Ergonomic mouse with long battery life', 29.99, 50),
  (4, 'Mechanical Keyboard', 'Accessories', 'RGB backlit mechanical keyboard', 89.99, 30),
  (5, '27" 4K Monitor', 'Monitors', 'High-resolution 4K UHD monitor', 349.99, 20),
  (6, 'Gaming Headset', 'Audio', 'Surround sound headset with microphone', 79.99, 40),
  (7, 'USB-C Hub', 'Accessories', 'Multiport adapter with HDMI, USB and SD slots', 39.99, 60),
  (8, 'External SSD 1TB', 'Storage', 'Fast portable SSD for data transfer', 119.99, 35),
  (9, 'Smartphone X', 'Mobile', 'Flagship smartphone with high-end camera', 899.99, 25),
  (10, 'Smartphone Mini', 'Mobile', 'Compact version of the Smartphone X', 699.99, 20),
  (11, 'Bluetooth Speaker', 'Audio', 'Portable wireless speaker with deep bass', 49.99, 50),
  (12, 'Portable Charger 10000mAh', 'Accessories', 'Compact power bank for mobile devices', 24.99, 70),
  (13, 'Smartwatch Pro', 'Wearables', 'Water-resistant smartwatch with heart-rate monitor', 249.99, 25),
  (14, 'Tablet 11"', 'Tablets', '11-inch tablet for entertainment and work', 499.99, 15),
  (15, 'Tablet 8"', 'Tablets', 'Compact 8-inch tablet with long battery life', 299.99, 20),
  (16, 'Action Camera', 'Cameras', 'Waterproof 4K action camera', 199.99, 30),
  (17, 'Drone Explorer', 'Drones', 'HD camera drone with GPS tracking', 599.99, 10),
  (18, 'HDMI Cable 2m', 'Cables', 'High-speed HDMI 2.1 cable (2 meters)', 9.99, 100),
  (19, 'Wireless Charger', 'Accessories', 'Fast charging pad for smartphones', 19.99, 60),
  (20, 'Smart Light Bulb', 'Smart Home', 'Wi-Fi enabled LED light bulb with app control', 14.99, 80),
  (21, 'Gaming Chair', 'Furniture', 'Ergonomic chair for gamers', 189.99, 12),
  (22, 'Desk Lamp', 'Lighting', 'Adjustable LED desk lamp with USB port', 39.99, 30),
  (23, 'Noise Cancelling Earbuds', 'Audio', 'Wireless earbuds with active noise cancellation', 149.99, 40),
  (24, 'Router AX6000', 'Networking', 'Wi-Fi 6 router with ultra-fast connection', 249.99, 18),
  (25, 'USB Flash Drive 64GB', 'Storage', 'Compact USB 3.0 flash drive', 12.99, 90),
  (26, 'Smart Thermostat', 'Smart Home', 'Energy-saving smart thermostat', 129.99, 22),
  (27, 'Fitness Tracker', 'Wearables', 'Activity tracker with sleep monitoring', 99.99, 35),
  (28, 'Laptop Stand', 'Accessories', 'Aluminum adjustable laptop stand', 34.99, 45),
  (29, 'Ergonomic Mouse Pad', 'Accessories', 'Mouse pad with wrist rest', 14.99, 70),
  (30, 'Webcam 1080p', 'Accessories', 'Full HD webcam with noise reduction mic', 59.99, 25),
  (31, 'Wireless Keyboard', 'Accessories', 'Slim wireless keyboard with numeric pad', 49.99, 40),
  (32, 'Graphic Tablet', 'Peripherals', 'Drawing tablet with pressure sensitivity', 229.99, 12),
  (33, 'Projector HD', 'Video', 'Home projector with HDMI and USB ports', 399.99, 10),
  (34, 'VR Headset', 'Gaming', 'Virtual reality headset compatible with PC', 499.99, 8),
  (35, 'Desktop Tower PC', 'Computers', 'High-end desktop PC for gaming and work', 1099.99, 7),
  (36, 'Bluetooth Adapter', 'Networking', 'USB Bluetooth 5.0 adapter', 15.99, 50),
  (37, 'Gaming Controller', 'Gaming', 'Wireless game controller for PC and consoles', 59.99, 30),
  (38, 'Mechanical Pencil', 'Office', 'High-precision mechanical pencil', 4.99, 100),
  (39, 'Office Chair', 'Furniture', 'Adjustable ergonomic office chair', 159.99, 15),
  (40, 'Desk Organizer', 'Office', 'Wooden desk organizer with compartments', 24.99, 25),
  (41, 'Smart Plug', 'Smart Home', 'Wi-Fi smart plug compatible with Alexa', 11.99, 60),
  (42, 'LED Strip Light', 'Lighting', 'RGB LED strip with remote control', 17.99, 50),
  (43, 'Surge Protector', 'Electrical', '6-outlet surge protector with USB ports', 22.99, 40),
  (44, 'Cable Management Box', 'Office', 'Box for hiding and organizing cables', 12.49, 35),
  (45, 'Wi-Fi Extender', 'Networking', 'Dual-band Wi-Fi range extender', 44.99, 25),
  (46, 'Mini Tripod', 'Accessories', 'Compact tripod for cameras and phones', 8.99, 60),
  (47, 'Streaming Microphone', 'Audio', 'Professional USB microphone for streaming', 129.99, 15),
  (48, 'Phone Holder', 'Accessories', 'Flexible phone holder for desk or bed', 9.49, 75),
  (49, 'Monitor Arm', 'Accessories', 'Adjustable arm mount for monitors', 79.99, 20),
  (50, 'Laptop Sleeve 15"', 'Accessories', 'Protective sleeve for 15-inch laptop', 25.99, 40),
  (51, 'Notebook Set', 'Office', 'Set of 3 notebooks with soft cover', 6.99, 90)
ON CONFLICT (id) DO NOTHING;
